apiVersion: v1
kind: ConfigMap
metadata:
  name: aegis-policy-config
data:
  default.rego: |
{{ .Values.policy.defaultRego | indent 4 }}
  policy.json: |
    {
      "restricted_endpoints": [
        "/admin"
      ]
    }
