apiVersion: v1
kind: Service
metadata:
  name: aegis-verifier
spec:
  selector:
    app: aegis-verifier
  ports:
    - name: http
      port: {{ .Values.verifier.port }}
      targetPort: {{ .Values.verifier.port }}
