{{- if or .Values.integrations.datadog.enabled .Values.integrations.splunk.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: aegis-integrations
data:
  {{- if .Values.integrations.datadog.enabled }}
  datadog-otlp-endpoint: "https://trace.agent.{{ .Values.integrations.datadog.site }}/api/v1/otlp"
  {{- end }}
  {{- if .Values.integrations.splunk.enabled }}
  splunk-hec-endpoint: {{ .Values.integrations.splunk.hecEndpoint | quote }}
  {{- end }}
{{- end }}
