{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: catenar-proxy
spec:
  podSelector:
    matchLabels:
      app: catenar-proxy
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.networkPolicy.proxyIngress.enabled }}
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.proxyIngress.namespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.proxyIngress.podSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ .Values.proxy.port }}
    {{- else }}
    []
    {{- end }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: catenar-verifier
      ports:
        - protocol: TCP
          port: {{ .Values.verifier.port }}
    {{- if .Values.redis.enabled }}
    - to:
        - podSelector:
            matchLabels:
              app: catenar-redis
      ports:
        - protocol: TCP
          port: 6379
    {{- end }}
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 4317
    {{- if .Values.networkPolicy.egress.dns.enabled }}
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: catenar-verifier
spec:
  podSelector:
    matchLabels:
      app: catenar-verifier
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: catenar-proxy
      ports:
        - protocol: TCP
          port: {{ .Values.verifier.port }}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 4317
    {{- if .Values.networkPolicy.egress.dns.enabled }}
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
    {{- range .Values.networkPolicy.egress.cloudCidrs }}
    - to:
        - ipBlock:
            cidr: {{ . | quote }}
      ports:
        - protocol: TCP
          port: 443
    {{- end }}
{{- end }}
